### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by moltak** [alexzaitsev/freepager#5]
```
06-09 13:47:21.658 1452-1452/com.moltak.expViews E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.moltak.expViews, PID: 1452 java.lang.NullPointerException: 
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference 
at pro.alexzaitsev.freepager.library.view.core.VerticalPager.getScrollYForPage(VerticalPager.java:251)
at pro.alexzaitsev.freepager.library.view.core.VerticalPager.onMeasure(VerticalPager.java:318)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
```

I didn't add any view when activity's 'initialize time'. So there are no any views in VerticalPager.

**Comment by alexzaitsev** [comment]
@moltak you mean that you don't call `verticalPager.setFactory(this);`?
